name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-train-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r notebooks/tourism_project/deployment/requirements.txt

      - name: Verify Dataset Files
        run: |
          ls notebooks/tourism_project/data
          echo "Dataset files found"

      - name: Verify Model File
        run: |
          ls notebooks/tourism_project/model_building
          echo "Model file found"

      - name: Verify Deployment Files
        run: |
          ls notebooks/tourism_project/deployment
          echo "Deployment files found"

      - name: Pipeline Success
        run: |
          echo "Tourism MLOps Pipeline Executed Successfully"